#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  liftStop,       sensorTouch)
#pragma config(Sensor, dgtl6,  claw,           sensorDigitalOut)
#pragma config(Motor,  port1,           rightWheel1,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftWheel1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightWheel2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightLift1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightLift3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftLift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftLift3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftWheel2,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JonLib2/JonLib2.h"

void setLeftWheelSpeed (int speed) {
	motor[leftWheel1] = speed;
	motor[leftWheel2] = speed;
}

void setRightWheelSpeed (int speed) {
	motor[rightWheel1] = speed;
	motor[rightWheel2] = speed;
}

void lift (int power) {
	motor[leftLift1] = power;
	motor[leftLift2] = power;
	motor[leftLift3] = power;
	motor[rightLift1] = power;
	motor[rightLift2] = power;
	motor[rightLift3] = power;
}

task motorPortTest() {
	while(true) {
		motor[port1] 	= vexRT(Btn7U)*127; //rightWheel1
		motor[port2] 	= vexRT(Btn7D)*127; //leftWheel1
		motor[port3] 	= vexRT(Btn7L)*127; //rightWheel2 R
		motor[port4] 	= vexRT(Btn7R)*127; //rightLift1 R
		motor[port5] 	= vexRT(Btn8U)*127; //leftLift1
		motor[port6] 	= vexRT(Btn8D)*127; //rightLift2 R
		motor[port7] 	= vexRT(Btn8L)*127; //rightLift3
		motor[port8] 	= vexRT(Btn8R)*127; //leftLift2 R
		motor[port9] 	= vexRT(Btn5U)*127; //leftLift3
		motor[port10]	= vexRT(Btn6U)*127; //leftDrive2
	}
}

void pre_auton() { }

task autonomous () {

}

task usercontrol() {
	while(true) {
		tankDrive(vexRT[Ch3], vexRT[Ch2], 10);

		if(vexRT[Btn5U])
			lift(127);
		else if(vexRT[Btn5D] && !SensorValue[liftStop])
			lift((!SensorValue[liftStop])*-80);
		else if(SensorValue[liftStop]) //hold down code
			lift(-10);
		else
			lift(15);

		if(vexRT[Btn6U]) {
			SensorValue[claw] = !SensorValue[claw];
			while(vexRT[Btn6U]) { delay(5); }
		}

	}
}
